[package]
name = "legible-lang"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[[bin]]
name = "legible"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
miette = { version = "7", features = ["fancy"] }
sdl2 = { version = "0.37", features = ["ttf"] }
png = "0.17"
tiny_http = { version = "0.12", features = ["ssl-rustls"] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
argon2 = "0.5"
capstone = "0.13"
rand_core = { version = "0.6", features = ["getrandom"] }
ureq = "2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pretty_assertions = "1"

[[bench]]
name = "interpreter_bench"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
